In [1]:
import numpy as np

In [12]:
def left(s_i,s_j):
    if(s_j==0):
        i,j =   (s_i,s_j)
    else:
        i,j =   (s_i,s_j-1)
    if((i==2 or i==3 ) and j==2):
        return s_i,s_j
    return i,j

def up(s_i,s_j):
    
    if(s_i==0):
        i,j =  (s_i,s_j)
    else:
        i,j =   (s_i-1,s_j)
    if((i==2 or i==3 ) and j==2):
        return s_i,s_j
    return i,j

def reward(ns_i,ns_j):
    if(ns_i == 4 and ns_j == 2):
        r = -10
    elif(ns_i == 4 and ns_j == 4):
        r = 10
    else:
        r = 0
    return r

def down(s_i,s_j):
    if(s_i==4):
        i,j =   (s_i,s_j)
    else:
        i,j =   (s_i+1,s_j)
    if((i==2 or i==3 ) and j==2):
        return s_i,s_j
    return i,j


def right(s_i,s_j):
    if(s_j==4):
        i,j =   (s_i,s_j)
    else:
        i,j =   (s_i,s_j+1)
    if((i==2 or i==3 ) and j==2):
        return s_i,s_j
    return i,j


def find_max_action(s,a,prev_V,print_debug=False):
    s_i,s_j = s
    
    for action in a:
        sum_v = 0 
        if(action == 0):#UP
            
            ns_i,ns_j = up(s_i,s_j)
            ls_i,ls_j = left(s_i,s_j)
            rs_i,rs_j = right(s_i,s_j)
            r = reward(ns_i,ns_j)
            sr = reward(s_i,s_j)
            lr = reward(ls_i,ls_j)
            rr = reward(rs_i,rs_j)            
            sum_v += 0.8 * (r + prev_V[ns_i][ns_j]) 
            sum_v += 0.1 * (sr + prev_V[s_i][s_j])
            sum_v += 0.05 * (lr + prev_V[ls_i][ls_j])
            sum_v += 0.05 * (rr + prev_V[rs_i][rs_j])   
            
            max_action = sum_v;
            if(print_debug):
                print "CAME IN TAKING UP ACTION"
                print r,sr,lr,rr
                print 0.8 * (r + prev_V[ns_i][ns_j]) , 0.1 * (sr + prev_V[s_i][s_j]), 0.05 * (lr + prev_V[ls_i][ls_j]),0.05 * (rr + prev_V[rs_i][rs_j]) 

                print sum_v
        elif(action == 1):#LEFT
            
            ns_i,ns_j = left(s_i,s_j)
            ls_i,ls_j = up(s_i,s_j)
            rs_i,rs_j = down(s_i,s_j)
            r = reward(ns_i,ns_j)
            sr = reward(s_i,s_j)
            lr = reward(ls_i,ls_j)
            rr = reward(rs_i,rs_j)

            sum_v += 0.8 * (r + prev_V[ns_i][ns_j]) 
            sum_v += 0.1 * (sr + prev_V[s_i][s_j])
            sum_v += 0.05 * (lr + prev_V[ls_i][ls_j])
            sum_v += 0.05 * (rr + prev_V[rs_i][rs_j]) 
            max_action = max(sum_v,max_action);
            if(print_debug):
                print "CAME IN TAKING LEFT ACTION"
                print r,sr,lr,rr
                print 0.8 * (r + prev_V[ns_i][ns_j]) , 0.1 * (sr + prev_V[s_i][s_j]), 0.05 * (lr + prev_V[ls_i][ls_j]),0.05 * (rr + prev_V[rs_i][rs_j]) 

                print sum_v
        elif(action == 2):#DOWN

            ns_i,ns_j = down(s_i,s_j)
            ls_i,ls_j = left(s_i,s_j)
            rs_i,rs_j = right(s_i,s_j)
            r = reward(ns_i,ns_j)
            sr = reward(s_i,s_j)
            lr = reward(ls_i,ls_j)
            rr = reward(rs_i,rs_j)            
            sum_v += (0.8 * (r + prev_V[ns_i][ns_j]) )
            sum_v += (0.1 * (sr + prev_V[s_i][s_j]))
            sum_v += (0.05 * (lr + prev_V[ls_i][ls_j]))
            sum_v += (0.05 * (rr + prev_V[rs_i][rs_j])  )
            max_action = max(sum_v,max_action);
            if(print_debug):
                print "CAME IN TAKING DOWN ACTION"
                print r,sr,lr,rr
                print 0.8 * (r + prev_V[ns_i][ns_j]) , 0.1 * (sr + prev_V[s_i][s_j]), 0.05 * (lr + prev_V[ls_i][ls_j]),0.05 * (rr + prev_V[rs_i][rs_j]) 

                print sum_v
        elif(action == 3):#RIGHT
            
            ns_i,ns_j = right(s_i,s_j)
            ls_i,ls_j = up(s_i,s_j)
            rs_i,rs_j = down(s_i,s_j)
            r = reward(ns_i,ns_j)
            sr = reward(s_i,s_j)
            lr = reward(ls_i,ls_j)
            rr = reward(rs_i,rs_j)            
            sum_v += 0.8 * (r + prev_V[ns_i][ns_j]) 
            sum_v += 0.1 * (sr + prev_V[s_i][s_j])
            sum_v += 0.05 * (lr + prev_V[ls_i][ls_j])
            sum_v += 0.05 * (rr + prev_V[rs_i][rs_j]) 
            max_action = max(sum_v,max_action);
            if(print_debug):
                print "CAME IN TAKING RIGHT ACTION"
                print r,sr,lr,rr
                print 0.8 * (r + prev_V[ns_i][ns_j]) , 0.1 * (sr + prev_V[s_i][s_j]), 0.05 * (lr + prev_V[ls_i][ls_j]),0.05 * (rr + prev_V[rs_i][rs_j]) 
                print sum_v
    return max_action
                


def Value_Iteration(prev_V,deb=False):
    V = np.zeros(prev_V.shape)
    r,c = V.shape
    for i in range(r):
        for j in range(c):
            if((i==2 and j==2) or (i==3 and j==2) or (i==4 and j==4)):
                continue;
            else:
                if(deb):
                    print "STATE IS " + str(i)+" , "+ str(j)
                s = (i,j)
                a = [0,1,2,3]
                V[i][j] = find_max_action(s,a,prev_V,deb)
    return V


In [20]:
# prev_V= [[0,0,0,0,0],
#         [0,0,0,0,0],
#         [0,0,-10000,0,0],
#         [0,0,-10000,0,0],
#         [0,0,0,0,0]
#         ]
# prev_V = np.array(prev_V)
# for i in range(10):
#     prev_V = Value_Iteration(prev_V)
#     print prev_V
    
prev_V= [[0,0,0,0,0],
        [0,0,0,0,0],
        [0,0,-10000,0,0],
        [0,0,-10000,0,0],
        [0,0,0,0,0]
        ]
import sys


def print_table(V):
    r,c = V.shape
    for i in range(r):
        for j in range(c):
            if(j==c-1):
                print V[i][j],"\\\\"
            else:
                sys.stdout.write(str(V[i][j]) + " & ")
    print


prev_V = np.array(prev_V) 
for i in range(10):
    prev_V = np.around(Value_Iteration(prev_V,False),decimals=3)
    print_table(prev_V)
    


0.0 & 0.0 & 0.0 & 0.0 & 0.0 \\
0.0 & 0.0 & 0.0 & 0.0 & 0.0 \\
0.0 & 0.0 & 0.0 & 0.0 & 0.0 \\
0.0 & 0.0 & 0.0 & 0.0 & 8.0 \\
0.0 & 0.0 & -2.0 & 8.0 & 0.0 \\

0.0 & 0.0 & 0.0 & 0.0 & 0.0 \\
0.0 & 0.0 & 0.0 & 0.0 & 0.0 \\
0.0 & 0.0 & 0.0 & 0.0 & 6.4 \\
0.0 & 0.0 & 0.0 & 6.8 & 9.2 \\
0.0 & 0.0 & 4.0 & 9.2 & 0.0 \\

0.0 & 0.0 & 0.0 & 0.0 & 0.0 \\
0.0 & 0.0 & 0.0 & 0.0 & 5.12 \\
0.0 & 0.0 & 0.0 & 5.76 & 8.32 \\
0.0 & 0.0 & 0.0 & 8.84 & 9.72 \\
0.0 & 0.0 & 6.16 & 9.72 & 0.0 \\

0.0 & 0.0 & 0.0 & 0.0 & 4.096 \\
0.0 & 0.0 & 0.0 & 4.864 & 7.424 \\
0.0 & 0.0 & 0.0 & 8.352 & 9.312 \\
0.0 & 0.0 & 0.0 & 9.588 & 9.9 \\
0.0 & 0.0 & 7.008 & 9.9 & 0.0 \\

0.0 & 0.0 & 0.0 & 4.096 & 6.554 \\
0.0 & 0.0 & 3.891 & 7.539 & 8.806 \\
0.0 & 0.0 & 0.0 & 9.389 & 9.734 \\
0.0 & 0.0 & 0.0 & 9.853 & 9.964 \\
0.0 & 0.0 & 7.322 & 9.964 & 0.0 \\

0.0 & 0.0 & 3.471 & 6.768 & 8.233 \\
0.0 & 3.113 & 6.615 & 8.9 & 9.485 \\
0.0 & 0.0 & 0.0 & 9.777 & 9.901 \\
0.0 & 0.0 & 0.0 & 9.947 & 9.987 \\
0.0 & 0.0 & 7.436 & 9.987 & 0.0 

In [23]:
    
prev_V= [[0,0,0,0,0],
        [0,0,0,0,0],
        [0,0,-10000,0,0],
        [0,0,-10000,0,0],
        [0,0,0,0,0]
        ]
prev_V = np.array(prev_V) 

In [24]:
for i in range(1):
    prev_V = np.around(Value_Iteration(prev_V,True),decimals=3)
    print_table(prev_V)

STATE IS 0 , 0
CAME IN TAKING UP ACTION
0 0 0 0
0.0 0.0 0.0 0.0
0.0
CAME IN TAKING LEFT ACTION
0 0 0 0
0.0 0.0 0.0 0.0
0.0
CAME IN TAKING DOWN ACTION
0 0 0 0
0.0 0.0 0.0 0.0
0.0
CAME IN TAKING RIGHT ACTION
0 0 0 0
0.0 0.0 0.0 0.0
0.0
STATE IS 0 , 1
CAME IN TAKING UP ACTION
0 0 0 0
0.0 0.0 0.0 0.0
0.0
CAME IN TAKING LEFT ACTION
0 0 0 0
0.0 0.0 0.0 0.0
0.0
CAME IN TAKING DOWN ACTION
0 0 0 0
0.0 0.0 0.0 0.0
0.0
CAME IN TAKING RIGHT ACTION
0 0 0 0
0.0 0.0 0.0 0.0
0.0
STATE IS 0 , 2
CAME IN TAKING UP ACTION
0 0 0 0
0.0 0.0 0.0 0.0
0.0
CAME IN TAKING LEFT ACTION
0 0 0 0
0.0 0.0 0.0 0.0
0.0
CAME IN TAKING DOWN ACTION
0 0 0 0
0.0 0.0 0.0 0.0
0.0
CAME IN TAKING RIGHT ACTION
0 0 0 0
0.0 0.0 0.0 0.0
0.0
STATE IS 0 , 3
CAME IN TAKING UP ACTION
0 0 0 0
0.0 0.0 0.0 0.0
0.0
CAME IN TAKING LEFT ACTION
0 0 0 0
0.0 0.0 0.0 0.0
0.0
CAME IN TAKING DOWN ACTION
0 0 0 0
0.0 0.0 0.0 0.0
0.0
CAME IN TAKING RIGHT ACTION
0 0 0 0
0.0 0.0 0.0 0.0
0.0
STATE IS 0 , 4
CAME IN TAKING UP ACTION
0 0 0 0
0.0 0.0 0.0 0.0


In [25]:
print prev_V

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  8.]
 [ 0.  0. -2.  8.  0.]]


In [26]:
for i in range(1):
    prev_V = np.around(Value_Iteration(prev_V,True),decimals=3)
    print_table(prev_V)

STATE IS 0 , 0
CAME IN TAKING UP ACTION
0 0 0 0
0.0 0.0 0.0 0.0
0.0
CAME IN TAKING LEFT ACTION
0 0 0 0
0.0 0.0 0.0 0.0
0.0
CAME IN TAKING DOWN ACTION
0 0 0 0
0.0 0.0 0.0 0.0
0.0
CAME IN TAKING RIGHT ACTION
0 0 0 0
0.0 0.0 0.0 0.0
0.0
STATE IS 0 , 1
CAME IN TAKING UP ACTION
0 0 0 0
0.0 0.0 0.0 0.0
0.0
CAME IN TAKING LEFT ACTION
0 0 0 0
0.0 0.0 0.0 0.0
0.0
CAME IN TAKING DOWN ACTION
0 0 0 0
0.0 0.0 0.0 0.0
0.0
CAME IN TAKING RIGHT ACTION
0 0 0 0
0.0 0.0 0.0 0.0
0.0
STATE IS 0 , 2
CAME IN TAKING UP ACTION
0 0 0 0
0.0 0.0 0.0 0.0
0.0
CAME IN TAKING LEFT ACTION
0 0 0 0
0.0 0.0 0.0 0.0
0.0
CAME IN TAKING DOWN ACTION
0 0 0 0
0.0 0.0 0.0 0.0
0.0
CAME IN TAKING RIGHT ACTION
0 0 0 0
0.0 0.0 0.0 0.0
0.0
STATE IS 0 , 3
CAME IN TAKING UP ACTION
0 0 0 0
0.0 0.0 0.0 0.0
0.0
CAME IN TAKING LEFT ACTION
0 0 0 0
0.0 0.0 0.0 0.0
0.0
CAME IN TAKING DOWN ACTION
0 0 0 0
0.0 0.0 0.0 0.0
0.0
CAME IN TAKING RIGHT ACTION
0 0 0 0
0.0 0.0 0.0 0.0
0.0
STATE IS 0 , 4
CAME IN TAKING UP ACTION
0 0 0 0
0.0 0.0 0.0 0.0


In [27]:
print prev_V

[[ 0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   6.4]
 [ 0.   0.   0.   6.8  9.2]
 [ 0.   0.   4.   9.2  0. ]]


In [28]:
for i in range(1):
    prev_V = np.around(Value_Iteration(prev_V,True),decimals=3)
    print_table(prev_V)

STATE IS 0 , 0
CAME IN TAKING UP ACTION
0 0 0 0
0.0 0.0 0.0 0.0
0.0
CAME IN TAKING LEFT ACTION
0 0 0 0
0.0 0.0 0.0 0.0
0.0
CAME IN TAKING DOWN ACTION
0 0 0 0
0.0 0.0 0.0 0.0
0.0
CAME IN TAKING RIGHT ACTION
0 0 0 0
0.0 0.0 0.0 0.0
0.0
STATE IS 0 , 1
CAME IN TAKING UP ACTION
0 0 0 0
0.0 0.0 0.0 0.0
0.0
CAME IN TAKING LEFT ACTION
0 0 0 0
0.0 0.0 0.0 0.0
0.0
CAME IN TAKING DOWN ACTION
0 0 0 0
0.0 0.0 0.0 0.0
0.0
CAME IN TAKING RIGHT ACTION
0 0 0 0
0.0 0.0 0.0 0.0
0.0
STATE IS 0 , 2
CAME IN TAKING UP ACTION
0 0 0 0
0.0 0.0 0.0 0.0
0.0
CAME IN TAKING LEFT ACTION
0 0 0 0
0.0 0.0 0.0 0.0
0.0
CAME IN TAKING DOWN ACTION
0 0 0 0
0.0 0.0 0.0 0.0
0.0
CAME IN TAKING RIGHT ACTION
0 0 0 0
0.0 0.0 0.0 0.0
0.0
STATE IS 0 , 3
CAME IN TAKING UP ACTION
0 0 0 0
0.0 0.0 0.0 0.0
0.0
CAME IN TAKING LEFT ACTION
0 0 0 0
0.0 0.0 0.0 0.0
0.0
CAME IN TAKING DOWN ACTION
0 0 0 0
0.0 0.0 0.0 0.0
0.0
CAME IN TAKING RIGHT ACTION
0 0 0 0
0.0 0.0 0.0 0.0
0.0
STATE IS 0 , 4
CAME IN TAKING UP ACTION
0 0 0 0
0.0 0.0 0.0 0.0
